spring:
  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:mysql://shortline.proxy.rlwy.net:47411/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:dsuBKgsNgqWByQtochCssOIMttdLnEeD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    ddl-auto: create

  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: senko@outlook.com
    password: senko
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084


#spring:
#  datasource:
#      url: jdbc:mysql://shortline.proxy.rlwy.net:47411/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      username: root
#      password: dsuBKgsNgqWByQtochCssOIMttdLnEeD
#      driver-class-name: com.mysql.cj.jdbc.Driver
##      username: root
###      url: jdbc:mysql://localhost:3306/ecom_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
##      url: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
##      password: dsuBKgsNgqWByQtochCssOIMttdLnEeD
###      password: Khan@786
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        ddl-auto: update
#  mail:
#    host: smtp-mail.outlook.com
#    port: 587
#    username: senko@outlook.com
#    password: senko
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#server:
#  port: 8084
#
#
##  username: spring
##  url: jdbc:mysql://localhost:3306/web_store_test?useSSL=false
##  password: spring
#
