spring:
  datasource:
      username: root
      url: jdbc:mysql://localhost:3306/ecom_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      password: Khan@786
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: senko@outlook.com
    password: senko
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084
#
#
##  username: spring
##  url: jdbc:mysql://localhost:3306/web_store_test?useSSL=false
##  password: spring
#
